services:
  app:
    image: eat-score-api:dev
    build:
      target: development
    volumes:
      - ./api:/api
    environment:
      VERSION: "development"
  web:
    image: eat-score-web:dev
    build:
      target: development
    volumes:
      - ./web:/web
    environment:
      REACT_APP_VERSION: "development"
