services:
  db:
    image: eat-score-db-with-data
    ports:
      - "5432:5432"
    stop_grace_period: 1s
  app:
    build:
      context: api
    stop_grace_period: 1s
    ports:
      - "8080:8080"
  web:
    build:
      context: web
    stop_grace_period: 1s
    ports:
      - "3000:3000"
