ARG HOST="192.168.1.231"
ARG USER="hrgn"
ARG DATABASE_NAME="eat_score"
ARG PRE_FILE="pre.sql"
ARG POST_FILE="post.sql"
ARG LOCALE_LANG="en_DK"
ARG TZ="Europe/Copenhagen"

FROM ghcr.io/frederikhs/local-db-copy:latest
